%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/humble/.*$
%global __requires_exclude_from ^/opt/ros/humble/.*$

Name:           ros-humble-py-trees-ros-tutorials
Version:        2.3.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS py_trees_ros_tutorials package

License:        BSD
URL:            https://py-trees-ros-tutorials.readthedocs.io/en/release-2.0.x/
Source0:        %{name}-%{version}.tar.gz

Requires:       libXext-devel
Requires:       python%{python3_pkgversion}-qt5-devel
Requires:       python%{python3_pkgversion}-sip-devel
Requires:       redhat-rpm-config
Requires:       ros-humble-action-msgs
Requires:       ros-humble-geometry-msgs
Requires:       ros-humble-launch
Requires:       ros-humble-launch-ros
Requires:       ros-humble-py-trees
Requires:       ros-humble-py-trees-ros
Requires:       ros-humble-py-trees-ros-interfaces
Requires:       ros-humble-rcl-interfaces
Requires:       ros-humble-rclpy
Requires:       ros-humble-ros2launch
Requires:       ros-humble-ros2param
Requires:       ros-humble-ros2run
Requires:       ros-humble-ros2service
Requires:       ros-humble-ros2topic
Requires:       ros-humble-sensor-msgs
Requires:       ros-humble-std-msgs
Requires:       ros-humble-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  python%{python3_pkgversion}-setuptools
BuildRequires:  python3-qt5-devel
BuildRequires:  qt5-qttools-devel
BuildRequires:  ros-humble-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  ros-humble-action-msgs
BuildRequires:  ros-humble-py-trees
BuildRequires:  ros-humble-py-trees-ros
BuildRequires:  ros-humble-rclpy
%endif

%description
Tutorials for py_trees on ROS2.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/humble"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/humble

%changelog
* Thu Jan 23 2025 Daniel Stonier <d.stonier@gmail.com> - 2.3.0-1
- Autogenerated by Bloom

