%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-py-trees-ros-tutorials
Version:        2.3.0
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS py_trees_ros_tutorials package

License:        BSD
URL:            https://py-trees-ros-tutorials.readthedocs.io/en/release-2.0.x/
Source0:        %{name}-%{version}.tar.gz

Requires:       libXext-devel
Requires:       python3-qt5-devel
Requires:       python3-sip-devel
Requires:       ros-kilted-action-msgs
Requires:       ros-kilted-geometry-msgs
Requires:       ros-kilted-launch
Requires:       ros-kilted-launch-ros
Requires:       ros-kilted-py-trees
Requires:       ros-kilted-py-trees-ros
Requires:       ros-kilted-py-trees-ros-interfaces
Requires:       ros-kilted-rcl-interfaces
Requires:       ros-kilted-rclpy
Requires:       ros-kilted-ros2launch
Requires:       ros-kilted-ros2param
Requires:       ros-kilted-ros2run
Requires:       ros-kilted-ros2service
Requires:       ros-kilted-ros2topic
Requires:       ros-kilted-sensor-msgs
Requires:       ros-kilted-std-msgs
Requires:       ros-kilted-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  python%{python3_pkgversion}-setuptools
BuildRequires:  python3-qt5-devel
BuildRequires:  qt5-qttools-devel
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  ros-kilted-action-msgs
BuildRequires:  ros-kilted-py-trees
BuildRequires:  ros-kilted-py-trees-ros
BuildRequires:  ros-kilted-rclpy
%endif

%description
Tutorials for py_trees on ROS2.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/kilted"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Tue Apr 22 2025 Daniel Stonier <d.stonier@gmail.com> - 2.3.0-2
- Autogenerated by Bloom

* Thu Jan 23 2025 Daniel Stonier <d.stonier@gmail.com> - 2.3.0-1
- Autogenerated by Bloom

